name: Deploy to Server

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Generate poetry.lock if not exists
        run: |
          if [ ! -f poetry.lock ]; then
            poetry lock --no-update
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/ilyasvinarenko/mysite:${{ github.sha }}
            ghcr.io/ilyasvinarenko/mysite:latest

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_LOGIN: ${{ secrets.SERVER_LOGIN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          
          # Команда для деплоя на сервер
          ssh -i private_key.pem $SERVER_LOGIN@$SERVER_IP "
            # Логинимся в GitHub Container Registry
            sudo docker login ghcr.io -u ilyasvinarenko -p '${{ secrets.DEPLOY_TOKEN }}'
            
            # Останавливаем и удаляем старый контейнер
            sudo docker stop mysite || true
            sudo docker rm mysite || true
            
            # Запускаем новый контейнер
            sudo docker run -d \
              --name mysite \
              -p 8000:8000 \
              ghcr.io/ilyasvinarenko/mysite:${{ github.sha }}
          "
          
          # Очищаем временные файлы
          rm -f private_key.pem